const String baseURL = "http://172.93.54.177:3002";
const String sendOtpEndpoint = "/driver/signin"; //POST
const String veriftOtpEndpoint = "/driver/confirmation"; //POST
const String resendOtpEndpoint = "/driver/resendotp"; //POST
const String complpeteSignUpEndpoint = "/driver/complete"; //POST
const String logOutEndpoint = "/driver/logout"; //POST
const String getUserPofileEndpoint = "/driver/profile/preview"; //GET
const String updatePofileEndpoint = "/driver/profile/update"; //PUT
const String updloadProfileImageEndpoint = "/driver/profile/upload"; //PUT
const String updloadDocumentEndpoint = "/driver/document/upload"; //PUT
